### ISSUE TITLE
PatternSyntaxError when there is environment variable with backslashes

### ISSUE THREAD

**Issue by stirante** [DmitriiShamrikov/mslinks#26]
In case there is a environment variable name, that contains backslashes, the method `createLink` fails. 
```
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 12
%\\.\Global\Motherboard Resources\PATHS%
            ^
at java.base/java.util.regex.Pattern.error(Pattern.java:2015)
at java.base/java.util.regex.Pattern.escape(Pattern.java:2604)
at java.base/java.util.regex.Pattern.atom(Pattern.java:2273)
at java.base/java.util.regex.Pattern.sequence(Pattern.java:2197)
at java.base/java.util.regex.Pattern.expr(Pattern.java:2056)
at java.base/java.util.regex.Pattern.compile(Pattern.java:1778)
at java.base/java.util.regex.Pattern.<init>(Pattern.java:1427)
at java.base/java.util.regex.Pattern.compile(Pattern.java:1094)
at mslinks.ShellLink.resolveEnvVariables(ShellLink.java:395)
at mslinks.ShellLink.setTarget(ShellLink.java:336)
at mslinks.ShellLink.createLink(ShellLink.java:380)
```

Looks like just adding `replace("\\", "\\\\");` might fix the problem

**Comment by DmitriiShamrikov** [comment]
should be fixed in 1.0.7
