### ISSUE TITLE
Regression with deprecated ShellLink.createLink(...)

### ISSUE THREAD

**Issue by tresf** [DmitriiShamrikov/mslinks#35]
This code worked in 1.0.4, but is broken in 1.0.7:

```java
ShellLink.createLink("C:\\Windows\\notepad.exe", "C:\\Users\\Owner\\Desktop\\Start Notepad.lnk");
```

Error:

```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <<> at index 0: <unknown>
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at mslinks.ShellLinkHelper.saveTo(ShellLinkHelper.java:153)
	at mslinks.ShellLink.saveTo(ShellLink.java:330)
	at mslinks.ShellLink.createLink(ShellLink.java:366)
	at LinkBug.main(LinkBug.java:5)
```

Workaround:

* Switch away from the deprecated API to the new API:
```java
ShellLinkHelper.createLink("C:\\Windows\\notepad.exe", "C:\\Users\\Owner\\Desktop\\Start Notepad.lnk");
```

**Comment by DmitriiShamrikov** [comment]
I fixed this, see 1.0.8
